-- =====================================================================================
--  ARQUIVO 4: DIMENSÕES CUSTOMIZADAS + TABELA PONTE
-- =====================================================================================
--  Rode depois de: 01-carga-staging.sql, 02-dimensoes-prontas.sql e 03-diagnostico.sql
--
--  Este arquivo cria e carrega as dimensões que faltam no modelo estrela:
--    1. dim_categoria      - 38 linhas (37 grafias + linha -1)
--    2. dim_praca          - 13 linhas (12 pracas + linha -1)
--    3. bridge_loja_praca  - 48 linhas (loja x praca com fator de rateio)
--
--  Transformacões aplicadas:
--    - De-para de categorias com CASE WHEN na ordem lógica correta
--      (MED antes de RA para "Racão Medicamentosa" ir para Medicamento);
--    - UPPER + TRANSLATE para padronizar maiúsculas e remover acentos;
--    - Conversão de domicilios_com_pet de texto para inteiro;
--    - Conversão de percentual de público de texto para decimal;
--    - Linha -1 em todas as dimensões para evitar FK nula na fato.
-- =====================================================================================

-- =====================================================================================
--  DIM_CATEGORIA
--  grao: UMA GRAFIA DA ORIGEM
-- =====================================================================================
DROP TABLE IF EXISTS dim_categoria;
CREATE TABLE dim_categoria (
    sk_categoria     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria_origem VARCHAR(50),
    nome_categoria   VARCHAR(30),
    grupo_categoria  VARCHAR(20)
);

-- Linha -1
INSERT INTO dim_categoria (sk_categoria, categoria_origem, nome_categoria, grupo_categoria)
VALUES (-1, 'Nao Informado', 'Nao Informado', 'Nao Informado');

-- Carga com o de-para na ordem lógica correta
INSERT INTO dim_categoria (categoria_origem, nome_categoria, grupo_categoria)
SELECT DISTINCT
    "CategoriaProduto",
    CASE
        WHEN UPPER("CategoriaProduto") LIKE '%MED%' THEN 'Medicamento'
        WHEN UPPER("CategoriaProduto") LIKE '%PETISC%' THEN 'Petisco'
        WHEN UPPER("CategoriaProduto") LIKE '%RA%' THEN 'Racao'
        WHEN UPPER("CategoriaProduto") LIKE '%HIG%' THEN 'Higiene'
        WHEN UPPER("CategoriaProduto") LIKE '%BRINQ%' THEN 'Brinquedo'
        WHEN UPPER("CategoriaProduto") LIKE '%ACESS%' THEN 'Acessorio'
        WHEN UPPER("CategoriaProduto") LIKE '%SERV%' THEN 'Servico'
        ELSE 'Nao Informado'
    END AS nome_categoria,
    CASE
        WHEN UPPER("CategoriaProduto") LIKE '%MED%' THEN 'Saude e Higiene'
        WHEN UPPER("CategoriaProduto") LIKE '%PETISC%' THEN 'Alimentacao'
        WHEN UPPER("CategoriaProduto") LIKE '%RA%' THEN 'Alimentacao'
        WHEN UPPER("CategoriaProduto") LIKE '%HIG%' THEN 'Saude e Higiene'
        WHEN UPPER("CategoriaProduto") LIKE '%BRINQ%' THEN 'Bem-estar'
        WHEN UPPER("CategoriaProduto") LIKE '%ACESS%' THEN 'Bem-estar'
        WHEN UPPER("CategoriaProduto") LIKE '%SERV%' THEN 'Bem-estar'
        ELSE 'Nao Informado'
    END AS grupo_categoria
FROM stg_pedido;

-- =====================================================================================
--  DIM_PRACA
--  grao: UMA PRACA DE ATENDIMENTO
-- =====================================================================================
DROP TABLE IF EXISTS dim_praca;
CREATE TABLE dim_praca (
    sk_praca           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_praca          VARCHAR(10),
    nome_praca         VARCHAR(60),
    regional           VARCHAR(30),
    domicilios_com_pet INT
);

-- Linha -1
INSERT INTO dim_praca (sk_praca, cod_praca, nome_praca, regional, domicilios_com_pet)
VALUES (-1, 'N/I', 'Nao Informado', 'Nao Informado', NULL);

-- Carga da dim_praca
INSERT INTO dim_praca (cod_praca, nome_praca, regional, domicilios_com_pet)
SELECT DISTINCT
    "CodPraca",
    "NomePraca",
    "Regional",
    CAST(REPLACE("DomiciliosComPet", '.', '') AS INT)
FROM stg_loja_praca;

-- =====================================================================================
--  BRIDGE_LOJA_PRACA
--  grao: UMA LOJA x UMA PRACA
-- =====================================================================================
DROP TABLE IF EXISTS bridge_loja_praca;
CREATE TABLE bridge_loja_praca (
    cod_loja      VARCHAR(10),
    sk_praca      INT,
    fator_publico DECIMAL(6,4),
    PRIMARY KEY (cod_loja, sk_praca)
);

-- Carga da ponte
INSERT INTO bridge_loja_praca (cod_loja, sk_praca, fator_publico)
SELECT
    "CodLoja",
    d.sk_praca,
    CAST("PercentualPublico" AS DECIMAL(6,4))
FROM stg_loja_praca s
JOIN dim_praca d ON d.cod_praca = s."CodPraca";

-- =====================================================================================
--  CONFERÊNCIA
-- =====================================================================================
SELECT 'dim_categoria' AS tabela, COUNT(*) AS linhas, '38' AS esperado FROM dim_categoria
UNION ALL SELECT 'dim_praca', COUNT(*), '13' FROM dim_praca
UNION ALL SELECT 'bridge_loja_praca', COUNT(*), '48' FROM bridge_loja_praca;