-- =====================================================================================
--  ARQUIVO 4: DIMENSOES CUSTOMIZADAS + TABELA PONTE
--  Case: Pata Amiga  |  PostgreSQL 16+
-- =====================================================================================
--  Rode depois de: 01-carga-staging.sql e 02-dimensoes-prontas.sql
--
--  Este arquivo cria e carrega:
--    1. dim_categoria      (38 linhas: 37 grafias + a linha -1)
--    2. dim_praca          (13 linhas: 12 pracas + a linha -1)
--    3. bridge_loja_praca  (48 linhas: uma loja x uma praca)
--
--  Regras aplicadas:
--    - Toda dimensao tem a linha -1 = "Nao Informado";
--    - A grafia crua e guardada em categoria_origem;
--    - O de-para de categoria segue a ORDEM LOGICA do documento;
--    - A comparacao usa UPPER + TRANSLATE (sem acento), cobrindo 18 acentos
--      (maiusculos e minusculos), incluindo cedilha;
--    - O fator de publico da ponte soma 1,00 por loja.
-- =====================================================================================

-- =====================================================================================
--  DIM_CATEGORIA
-- =====================================================================================
DROP TABLE IF EXISTS dim_categoria;
CREATE TABLE dim_categoria (
    sk_categoria     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria_origem VARCHAR(50),
    nome_categoria   VARCHAR(30),
    grupo_categoria  VARCHAR(20)
);

INSERT INTO dim_categoria (sk_categoria, categoria_origem, nome_categoria, grupo_categoria)
VALUES (-1, 'Nao Informado', 'Nao Informado', 'Nao Informado');

INSERT INTO dim_categoria (categoria_origem, nome_categoria, grupo_categoria)
SELECT DISTINCT
    "CategoriaProduto",
    CASE
        WHEN UPPER(TRANSLATE("CategoriaProduto", U&'\00C1\00C9\00CD\00D3\00DA\00C0\00C8\00CC\00D2\00D9\00C2\00CA\00CE\00D4\00DB\00C3\00D5\00C7\00E1\00E9\00ED\00F3\00FA\00E0\00E8\00EC\00F2\00F9\00E2\00EA\00EE\00F4\00FB\00E3\00F5\00E7', 'AEIOUAEIOUAEIOUAOCaeiouaeiouaeiouaoc')) LIKE '%MED%' THEN 'Medicamento'
        WHEN UPPER(TRANSLATE("CategoriaProduto", U&'\00C1\00C9\00CD\00D3\00DA\00C0\00C8\00CC\00D2\00D9\00C2\00CA\00CE\00D4\00DB\00C3\00D5\00C7\00E1\00E9\00ED\00F3\00FA\00E0\00E8\00EC\00F2\00F9\00E2\00EA\00EE\00F4\00FB\00E3\00F5\00E7', 'AEIOUAEIOUAEIOUAOCaeiouaeiouaeiouaoc')) LIKE '%PETISC%' THEN 'Petisco'
        WHEN UPPER(TRANSLATE("CategoriaProduto", U&'\00C1\00C9\00CD\00D3\00DA\00C0\00C8\00CC\00D2\00D9\00C2\00CA\00CE\00D4\00DB\00C3\00D5\00C7\00E1\00E9\00ED\00F3\00FA\00E0\00E8\00EC\00F2\00F9\00E2\00EA\00EE\00F4\00FB\00E3\00F5\00E7', 'AEIOUAEIOUAEIOUAOCaeiouaeiouaeiouaoc')) LIKE '%RA%' THEN 'Racao'
        WHEN UPPER(TRANSLATE("CategoriaProduto", U&'\00C1\00C9\00CD\00D3\00DA\00C0\00C8\00CC\00D2\00D9\00C2\00CA\00CE\00D4\00DB\00C3\00D5\00C7\00E1\00E9\00ED\00F3\00FA\00E0\00E8\00EC\00F2\00F9\00E2\00EA\00EE\00F4\00FB\00E3\00F5\00E7', 'AEIOUAEIOUAEIOUAOCaeiouaeiouaeiouaoc')) LIKE '%HIG%' THEN 'Higiene'
        WHEN UPPER(TRANSLATE("CategoriaProduto", U&'\00C1\00C9\00CD\00D3\00DA\00C0\00C8\00CC\00D2\00D9\00C2\00CA\00CE\00D4\00DB\00C3\00D5\00C7\00E1\00E9\00ED\00F3\00FA\00E0\00E8\00EC\00F2\00F9\00E2\00EA\00EE\00F4\00FB\00E3\00F5\00E7', 'AEIOUAEIOUAEIOUAOCaeiouaeiouaeiouaoc')) LIKE '%BRINQ%' THEN 'Brinquedo'
        WHEN UPPER(TRANSLATE("CategoriaProduto", U&'\00C1\00C9\00CD\00D3\00DA\00C0\00C8\00CC\00D2\00D9\00C2\00CA\00CE\00D4\00DB\00C3\00D5\00C7\00E1\00E9\00ED\00F3\00FA\00E0\00E8\00EC\00F2\00F9\00E2\00EA\00EE\00F4\00FB\00E3\00F5\00E7', 'AEIOUAEIOUAEIOUAOCaeiouaeiouaeiouaoc')) LIKE '%ACESS%' THEN 'Acessorio'
        WHEN UPPER(TRANSLATE("CategoriaProduto", U&'\00C1\00C9\00CD\00D3\00DA\00C0\00C8\00CC\00D2\00D9\00C2\00CA\00CE\00D4\00DB\00C3\00D5\00C7\00E1\00E9\00ED\00F3\00FA\00E0\00E8\00EC\00F2\00F9\00E2\00EA\00EE\00F4\00FB\00E3\00F5\00E7', 'AEIOUAEIOUAEIOUAOCaeiouaeiouaeiouaoc')) LIKE '%SERV%' THEN 'Servico'
        ELSE 'Nao Informado'
    END AS nome_categoria,
    CASE
        WHEN UPPER(TRANSLATE("CategoriaProduto", U&'\00C1\00C9\00CD\00D3\00DA\00C0\00C8\00CC\00D2\00D9\00C2\00CA\00CE\00D4\00DB\00C3\00D5\00C7\00E1\00E9\00ED\00F3\00FA\00E0\00E8\00EC\00F2\00F9\00E2\00EA\00EE\00F4\00FB\00E3\00F5\00E7', 'AEIOUAEIOUAEIOUAOCaeiouaeiouaeiouaoc')) LIKE '%MED%' THEN 'Saude e Higiene'
        WHEN UPPER(TRANSLATE("CategoriaProduto", U&'\00C1\00C9\00CD\00D3\00DA\00C0\00C8\00CC\00D2\00D9\00C2\00CA\00CE\00D4\00DB\00C3\00D5\00C7\00E1\00E9\00ED\00F3\00FA\00E0\00E8\00EC\00F2\00F9\00E2\00EA\00EE\00F4\00FB\00E3\00F5\00E7', 'AEIOUAEIOUAEIOUAOCaeiouaeiouaeiouaoc')) LIKE '%PETISC%' THEN 'Alimentacao'
        WHEN UPPER(TRANSLATE("CategoriaProduto", U&'\00C1\00C9\00CD\00D3\00DA\00C0\00C8\00CC\00D2\00D9\00C2\00CA\00CE\00D4\00DB\00C3\00D5\00C7\00E1\00E9\00ED\00F3\00FA\00E0\00E8\00EC\00F2\00F9\00E2\00EA\00EE\00F4\00FB\00E3\00F5\00E7', 'AEIOUAEIOUAEIOUAOCaeiouaeiouaeiouaoc')) LIKE '%RA%' THEN 'Alimentacao'
        WHEN UPPER(TRANSLATE("CategoriaProduto", U&'\00C1\00C9\00CD\00D3\00DA\00C0\00C8\00CC\00D2\00D9\00C2\00CA\00CE\00D4\00DB\00C3\00D5\00C7\00E1\00E9\00ED\00F3\00FA\00E0\00E8\00EC\00F2\00F9\00E2\00EA\00EE\00F4\00FB\00E3\00F5\00E7', 'AEIOUAEIOUAEIOUAOCaeiouaeiouaeiouaoc')) LIKE '%HIG%' THEN 'Saude e Higiene'
        WHEN UPPER(TRANSLATE("CategoriaProduto", U&'\00C1\00C9\00CD\00D3\00DA\00C0\00C8\00CC\00D2\00D9\00C2\00CA\00CE\00D4\00DB\00C3\00D5\00C7\00E1\00E9\00ED\00F3\00FA\00E0\00E8\00EC\00F2\00F9\00E2\00EA\00EE\00F4\00FB\00E3\00F5\00E7', 'AEIOUAEIOUAEIOUAOCaeiouaeiouaeiouaoc')) LIKE '%BRINQ%' THEN 'Bem-estar'
        WHEN UPPER(TRANSLATE("CategoriaProduto", U&'\00C1\00C9\00CD\00D3\00DA\00C0\00C8\00CC\00D2\00D9\00C2\00CA\00CE\00D4\00DB\00C3\00D5\00C7\00E1\00E9\00ED\00F3\00FA\00E0\00E8\00EC\00F2\00F9\00E2\00EA\00EE\00F4\00FB\00E3\00F5\00E7', 'AEIOUAEIOUAEIOUAOCaeiouaeiouaeiouaoc')) LIKE '%ACESS%' THEN 'Bem-estar'
        WHEN UPPER(TRANSLATE("CategoriaProduto", U&'\00C1\00C9\00CD\00D3\00DA\00C0\00C8\00CC\00D2\00D9\00C2\00CA\00CE\00D4\00DB\00C3\00D5\00C7\00E1\00E9\00ED\00F3\00FA\00E0\00E8\00EC\00F2\00F9\00E2\00EA\00EE\00F4\00FB\00E3\00F5\00E7', 'AEIOUAEIOUAEIOUAOCaeiouaeiouaeiouaoc')) LIKE '%SERV%' THEN 'Bem-estar'
        ELSE 'Nao Informado'
    END AS grupo_categoria
FROM stg_pedido;

-- =====================================================================================
--  DIM_PRACA
-- =====================================================================================
DROP TABLE IF EXISTS dim_praca;
CREATE TABLE dim_praca (
    sk_praca           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_praca          VARCHAR(10),
    nome_praca         VARCHAR(60),
    regional           VARCHAR(30),
    domicilios_com_pet INT
);

INSERT INTO dim_praca (sk_praca, cod_praca, nome_praca, regional, domicilios_com_pet)
VALUES (-1, 'N/I', 'Nao Informado', 'Nao Informado', NULL);

INSERT INTO dim_praca (cod_praca, nome_praca, regional, domicilios_com_pet)
SELECT DISTINCT
    "CodPraca",
    "NomePraca",
    "Regional",
    CAST(REPLACE("DomiciliosComPet", '.', '') AS INT)
FROM stg_loja_praca;

-- =====================================================================================
--  BRIDGE_LOJA_PRACA
-- =====================================================================================
DROP TABLE IF EXISTS bridge_loja_praca;
CREATE TABLE bridge_loja_praca (
    cod_loja      VARCHAR(10),
    sk_praca      INT,
    fator_publico DECIMAL(6,4),
    PRIMARY KEY (cod_loja, sk_praca)
);

INSERT INTO bridge_loja_praca (cod_loja, sk_praca, fator_publico)
SELECT
    "CodLoja",
    d.sk_praca,
    CAST("PercentualPublico" AS DECIMAL(6,4))
FROM stg_loja_praca s
JOIN dim_praca d ON d.cod_praca = s."CodPraca";

-- =====================================================================================
--  CONFERENCIA
-- =====================================================================================
SELECT 'dim_categoria' AS tabela, COUNT(*) AS linhas, '38' AS esperado FROM dim_categoria
UNION ALL SELECT 'dim_praca', COUNT(*), '13' FROM dim_praca
UNION ALL SELECT 'bridge_loja_praca', COUNT(*), '48' FROM bridge_loja_praca;