-- =====================================================================================
--  ARQUIVO 5: CARGA DA FATO_PEDIDO

-- =====================================================================================
--  Rode depois de: 01-carga-staging.sql, 02-dimensoes-prontas.sql e
--  04-dimensoes-customizadas.sql
--
--  Este arquivo cria e carrega a fato_pedido com 4.044 linhas.
--  Grao: 1 linha = 1 pedido.
--
--  Regras:
--    - Um unico INSERT ... SELECT, sem subconsulta: so SELECT, JOIN, LEFT JOIN e CASE WHEN;
--    - A limpeza fica na dimensao, e a fato apenas procura a linha certa;
--    - Nenhuma FK fica nula: quando o dado falta, aponta para a linha -1;
--    - As cinco colunas de dias sao calculadas UMA vez aqui na carga.
-- =====================================================================================

CREATE EXTENSION IF NOT EXISTS unaccent;

DROP TABLE IF EXISTS fato_pedido;
CREATE TABLE fato_pedido (
    sk_pedido        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_pedido    VARCHAR(20),
    sk_tempo_pedido  INT NOT NULL,
    sk_tempo_entrega INT NOT NULL,
    sk_loja          INT NOT NULL,
    sk_categoria     INT NOT NULL,
    houve_desconto   VARCHAR(15),
    canal_pedido     VARCHAR(20),
    dt_pedido        TIMESTAMP,
    qt_itens         INT,
    vl_liquido       DECIMAL(15,2),
    dias_integracao_separacao INT,
    dias_separacao_nota       INT,
    dias_nota_despacho        INT,
    dias_despacho_entrega     INT,
    dias_total_ate_entrega    INT,
    CONSTRAINT fk_fato_tempo_pedido FOREIGN KEY (sk_tempo_pedido) REFERENCES dim_tempo(sk_tempo),
    CONSTRAINT fk_fato_tempo_entrega FOREIGN KEY (sk_tempo_entrega) REFERENCES dim_tempo(sk_tempo),
    CONSTRAINT fk_fato_loja FOREIGN KEY (sk_loja) REFERENCES dim_loja(sk_loja),
    CONSTRAINT fk_fato_categoria FOREIGN KEY (sk_categoria) REFERENCES dim_categoria(sk_categoria)
);

INSERT INTO fato_pedido (
    numero_pedido,
    sk_tempo_pedido,
    sk_tempo_entrega,
    sk_loja,
    sk_categoria,
    houve_desconto,
    canal_pedido,
    dt_pedido,
    qt_itens,
    vl_liquido,
    dias_integracao_separacao,
    dias_separacao_nota,
    dias_nota_despacho,
    dias_despacho_entrega,
    dias_total_ate_entrega
)
SELECT
    s."NumeroPedido",
    TO_CHAR(TO_TIMESTAMP(s."DtHoraPedido", 'MM/DD/YYYY HH12:MI AM'), 'YYYYMMDD')::int,
    CASE 
        WHEN s."DtEntregaCliente" = '' THEN -1
        ELSE TO_CHAR(s."DtEntregaCliente"::date, 'YYYYMMDD')::int
    END,
    COALESCE(dl.sk_loja, -1),
    COALESCE(dc.sk_categoria, -1),
    CASE
        WHEN UPPER(TRIM(s."HouveDesconto")) IN ('S', 'SIM', '1', 'X', 'TRUE', 'V') THEN 'Sim'
        WHEN UPPER(TRIM(s."HouveDesconto")) IN ('N', 'NAO', '0', 'FALSE', 'F') THEN 'Nao'
        ELSE 'Nao Informado'
    END,
    CASE
        WHEN UPPER(s."CanalPedido") LIKE '%WHATS%' THEN 'WhatsApp'
        WHEN UPPER(s."CanalPedido") LIKE '%APP%' THEN 'App'
        WHEN UPPER(s."CanalPedido") LIKE '%SITE%' THEN 'Site'
        WHEN UPPER(s."CanalPedido") LIKE '%LOJA%' THEN 'Loja Fisica'
        WHEN UPPER(s."CanalPedido") LIKE '%TEL%' THEN 'Telefone'
        ELSE 'Nao Informado'
    END,
    TO_TIMESTAMP(s."DtHoraPedido", 'MM/DD/YYYY HH12:MI AM'),
    CASE 
        WHEN TRIM(s."QTD.Itens") IN ('', '-', 'N/I', 'n/d') THEN NULL
        ELSE CAST(s."QTD.Itens" AS INT)
    END,
    CASE 
        WHEN TRIM(REPLACE(s."ValorLiquidoPedido(R$)",'R$','')) IN ('','-') THEN NULL
        WHEN s."ValorLiquidoPedido(R$)" LIKE '%,%'
             THEN CAST(REPLACE(REPLACE(REPLACE(REPLACE(s."ValorLiquidoPedido(R$)",'R$',''),' ',''),'.',''),',','.') AS DECIMAL(15,2))
        ELSE CAST(REPLACE(REPLACE(s."ValorLiquidoPedido(R$)",'R$',''),' ','') AS DECIMAL(15,2))
    END,
    CASE 
        WHEN s."Dt Separacao Estoque" = '' THEN NULL
        ELSE s."Dt Separacao Estoque"::date - TO_TIMESTAMP(s."DtHoraIntegracaoERP", 'MM/DD/YYYY HH12:MI AM')::date
    END,
    CASE 
        WHEN s."DtNotaFiscal" = '' THEN NULL
        ELSE s."DtNotaFiscal"::date - s."Dt Separacao Estoque"::date
    END,
    CASE 
        WHEN s."Dt_Despacho_Transportadora" = '' THEN NULL
        ELSE s."Dt_Despacho_Transportadora"::date - s."DtNotaFiscal"::date
    END,
    CASE 
        WHEN s."DtEntregaCliente" = '' THEN NULL
        ELSE s."DtEntregaCliente"::date - s."Dt_Despacho_Transportadora"::date
    END,
    CASE 
        WHEN s."DtEntregaCliente" = '' THEN NULL
        ELSE s."DtEntregaCliente"::date - TO_TIMESTAMP(s."DtHoraIntegracaoERP", 'MM/DD/YYYY HH12:MI AM')::date
    END
FROM stg_pedido s
LEFT JOIN dim_categoria dc ON dc.categoria_origem = s."CategoriaProduto"
LEFT JOIN dim_loja dl ON dl.chave_loja = 
    UPPER(
        UNACCENT(
            REPLACE(
                REPLACE(
                    CASE
                        WHEN UPPER(TRIM(s."Loja-Nome")) = 'PATA AMIGA BLUMENAL CENTRO' THEN 'PATA AMIGA BLUMENAU CENTRO'
                        WHEN UPPER(TRIM(s."Loja-Nome")) = 'PATA AMIGA FLORIPA NORTE' THEN 'PATA AMIGA FLORIANOPOLIS NORTE'
                        WHEN UPPER(TRIM(s."Loja-Nome")) = 'PATA AMIGA JGUA DO SUL' THEN 'PATA AMIGA JARAGUA DO SUL'
                        ELSE TRIM(s."Loja-Nome")
                    END,
                    '/SC', ''
                ),
                '  ', ' '
            )
        )
    );

SELECT COUNT(*) AS linhas, '4044' AS esperado FROM fato_pedido;